d_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^demo/', include("django_demo.urls", namespace="demo")),
]

django_demo/urls.py
from django.conf.urls import url

from django_demo import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^role/(?P<userId>\d+)$', views.role, name="role"),
    url(r'^role2$', views.role2, name="role2"),
]

django_demo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.db.models import Model


# 模型管理器
class UserManager(models.Manager):
    def get_queryset(self):
        return super(UserManager, self).get_queryset().filter(data_status=True)

    def create(self, name, age):
        user = User()
        user.name = name
        user.age = age
        return user


# 用户模型
class User(Model):
    name = models.CharField(max_length=255)
    age = models.IntegerField(db_column="age")
    data_status = models.BooleanField(default=True)
    user_manager = UserManager()

    # @classmethod
    # def create(cls, name, age):
    #     user = User()
    #     user.name = name
    #     user.age = age
    #     return user

    class Meta:
        db_table = "t_user"
        ordering = ["-age"]


class Role(Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User)

    class Meta:
        db_table = "t_role"

django_demo/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django_demo.models import User


def index(request):
    # request.GET.get("key")
    # request.GET.getlist("key")
    # request.POST["key"]
    # request.session["session"] = "sessionName"
    # request.session.get("session", "no login")
    # request.clear()
    # request.flush()
    # temp = loader.get_template("django_demo/index.html")
    # return HttpResponse(temp.render())
    params = {"users": User.user_manager.all()}
    return render(request, "django_demo/index.html", params)


def role(request, userId):
    user = User.user_manager.get(pk=userId)
    roles = user.role_set.all()
    params = {"roles": roles}
    return render(request, "django_demo/role.html", params)

def role2(request):
    userId = request.GET.get("userId")
    user = User.user_manager.get(pk=userId)
    roles = user.role_set.all()
    params = {"roles": roles}
    return render(request, "django_demo/role.html", params)

templates/django_demo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
    <div>header</div>
    <div>
        {% block content %}
            可以替换的地方。。。
        {% endblock %}
    </div>
    <div>end</div>
</body>
</html>

templates/django_demo/index.html
{% extends "django_demo/base.html" %}
{% block content %}
    {% for user in users %}
        <div>
            <span>姓名：</span><a href="role/{{ user.id }}">{{ user.name }}</a>
            <span>姓名：</span><a href="{% url 'demo:role2' %}?userId={{ user.id }}">{{ user.name }}</a>
            <span>年龄：{{ user.age }}</span>
        </div>
    {% endfor %}
{% endblock %}

templates/django_demo/role.html
{% extends "django_demo/base.html" %}
{% block content %}
    {% for role in roles %}
        <div>
            <span>角色名称：{{ role.name }}</span>
        </div>
    {% endfor %}
{% endblock %}